[project]
name = "pdflinkcheck"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdfminer-six>=20251107",
    "pdfplumber>=0.11.8",
    "pymupdf>=1.26.6",
    "rich>=14.2.0",
    "typer>=0.20.0",
]

[tool.setuptools.packages.find]
where = ["src"]  

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
